//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DalEf
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MDGeneralEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MDGeneralEntities object using the connection string found in the 'MDGeneralEntities' section of the application configuration file.
        /// </summary>
        public MDGeneralEntities() : base("name=MDGeneralEntities", "MDGeneralEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MDGeneralEntities object.
        /// </summary>
        public MDGeneralEntities(string connectionString) : base(connectionString, "MDGeneralEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MDGeneralEntities object.
        /// </summary>
        public MDGeneralEntities(EntityConnection connection) : base(connection, "MDGeneralEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MDGeneral_Enums_Language> MDGeneral_Enums_Language
        {
            get
            {
                if ((_MDGeneral_Enums_Language == null))
                {
                    _MDGeneral_Enums_Language = base.CreateObjectSet<MDGeneral_Enums_Language>("MDGeneral_Enums_Language");
                }
                return _MDGeneral_Enums_Language;
            }
        }
        private ObjectSet<MDGeneral_Enums_Language> _MDGeneral_Enums_Language;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MDGeneral_Enums_Currency> MDGeneral_Enums_Currency
        {
            get
            {
                if ((_MDGeneral_Enums_Currency == null))
                {
                    _MDGeneral_Enums_Currency = base.CreateObjectSet<MDGeneral_Enums_Currency>("MDGeneral_Enums_Currency");
                }
                return _MDGeneral_Enums_Currency;
            }
        }
        private ObjectSet<MDGeneral_Enums_Currency> _MDGeneral_Enums_Currency;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MDGeneral_Enums_TimeZone> MDGeneral_Enums_TimeZone
        {
            get
            {
                if ((_MDGeneral_Enums_TimeZone == null))
                {
                    _MDGeneral_Enums_TimeZone = base.CreateObjectSet<MDGeneral_Enums_TimeZone>("MDGeneral_Enums_TimeZone");
                }
                return _MDGeneral_Enums_TimeZone;
            }
        }
        private ObjectSet<MDGeneral_Enums_TimeZone> _MDGeneral_Enums_TimeZone;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vEnums_Currency> vEnums_Currency
        {
            get
            {
                if ((_vEnums_Currency == null))
                {
                    _vEnums_Currency = base.CreateObjectSet<vEnums_Currency>("vEnums_Currency");
                }
                return _vEnums_Currency;
            }
        }
        private ObjectSet<vEnums_Currency> _vEnums_Currency;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vEnums_Language> vEnums_Language
        {
            get
            {
                if ((_vEnums_Language == null))
                {
                    _vEnums_Language = base.CreateObjectSet<vEnums_Language>("vEnums_Language");
                }
                return _vEnums_Language;
            }
        }
        private ObjectSet<vEnums_Language> _vEnums_Language;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vEnums_TimeZone> vEnums_TimeZone
        {
            get
            {
                if ((_vEnums_TimeZone == null))
                {
                    _vEnums_TimeZone = base.CreateObjectSet<vEnums_TimeZone>("vEnums_TimeZone");
                }
                return _vEnums_TimeZone;
            }
        }
        private ObjectSet<vEnums_TimeZone> _vEnums_TimeZone;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MDGeneral_Enums_KindOfTransportation> MDGeneral_Enums_KindOfTransportation
        {
            get
            {
                if ((_MDGeneral_Enums_KindOfTransportation == null))
                {
                    _MDGeneral_Enums_KindOfTransportation = base.CreateObjectSet<MDGeneral_Enums_KindOfTransportation>("MDGeneral_Enums_KindOfTransportation");
                }
                return _MDGeneral_Enums_KindOfTransportation;
            }
        }
        private ObjectSet<MDGeneral_Enums_KindOfTransportation> _MDGeneral_Enums_KindOfTransportation;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MDGeneral_Enums_Location> MDGeneral_Enums_Location
        {
            get
            {
                if ((_MDGeneral_Enums_Location == null))
                {
                    _MDGeneral_Enums_Location = base.CreateObjectSet<MDGeneral_Enums_Location>("MDGeneral_Enums_Location");
                }
                return _MDGeneral_Enums_Location;
            }
        }
        private ObjectSet<MDGeneral_Enums_Location> _MDGeneral_Enums_Location;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vEnumsCashBox> vEnumsCashBox
        {
            get
            {
                if ((_vEnumsCashBox == null))
                {
                    _vEnumsCashBox = base.CreateObjectSet<vEnumsCashBox>("vEnumsCashBox");
                }
                return _vEnumsCashBox;
            }
        }
        private ObjectSet<vEnumsCashBox> _vEnumsCashBox;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vvEnumsCashBox> vvEnumsCashBox
        {
            get
            {
                if ((_vvEnumsCashBox == null))
                {
                    _vvEnumsCashBox = base.CreateObjectSet<vvEnumsCashBox>("vvEnumsCashBox");
                }
                return _vvEnumsCashBox;
            }
        }
        private ObjectSet<vvEnumsCashBox> _vvEnumsCashBox;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MDGeneral_Enums_CashBox> MDGeneral_Enums_CashBox
        {
            get
            {
                if ((_MDGeneral_Enums_CashBox == null))
                {
                    _MDGeneral_Enums_CashBox = base.CreateObjectSet<MDGeneral_Enums_CashBox>("MDGeneral_Enums_CashBox");
                }
                return _MDGeneral_Enums_CashBox;
            }
        }
        private ObjectSet<MDGeneral_Enums_CashBox> _MDGeneral_Enums_CashBox;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MDGeneral_Enums_Language EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMDGeneral_Enums_Language(MDGeneral_Enums_Language mDGeneral_Enums_Language)
        {
            base.AddObject("MDGeneral_Enums_Language", mDGeneral_Enums_Language);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MDGeneral_Enums_Currency EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMDGeneral_Enums_Currency(MDGeneral_Enums_Currency mDGeneral_Enums_Currency)
        {
            base.AddObject("MDGeneral_Enums_Currency", mDGeneral_Enums_Currency);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MDGeneral_Enums_TimeZone EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMDGeneral_Enums_TimeZone(MDGeneral_Enums_TimeZone mDGeneral_Enums_TimeZone)
        {
            base.AddObject("MDGeneral_Enums_TimeZone", mDGeneral_Enums_TimeZone);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vEnums_Currency EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovEnums_Currency(vEnums_Currency vEnums_Currency)
        {
            base.AddObject("vEnums_Currency", vEnums_Currency);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vEnums_Language EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovEnums_Language(vEnums_Language vEnums_Language)
        {
            base.AddObject("vEnums_Language", vEnums_Language);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vEnums_TimeZone EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovEnums_TimeZone(vEnums_TimeZone vEnums_TimeZone)
        {
            base.AddObject("vEnums_TimeZone", vEnums_TimeZone);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MDGeneral_Enums_KindOfTransportation EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMDGeneral_Enums_KindOfTransportation(MDGeneral_Enums_KindOfTransportation mDGeneral_Enums_KindOfTransportation)
        {
            base.AddObject("MDGeneral_Enums_KindOfTransportation", mDGeneral_Enums_KindOfTransportation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MDGeneral_Enums_Location EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMDGeneral_Enums_Location(MDGeneral_Enums_Location mDGeneral_Enums_Location)
        {
            base.AddObject("MDGeneral_Enums_Location", mDGeneral_Enums_Location);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vEnumsCashBox EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovEnumsCashBox(vEnumsCashBox vEnumsCashBox)
        {
            base.AddObject("vEnumsCashBox", vEnumsCashBox);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vvEnumsCashBox EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovvEnumsCashBox(vvEnumsCashBox vvEnumsCashBox)
        {
            base.AddObject("vvEnumsCashBox", vvEnumsCashBox);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MDGeneral_Enums_CashBox EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMDGeneral_Enums_CashBox(MDGeneral_Enums_CashBox mDGeneral_Enums_CashBox)
        {
            base.AddObject("MDGeneral_Enums_CashBox", mDGeneral_Enums_CashBox);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MDGeneralModel", Name="MDGeneral_Enums_CashBox")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MDGeneral_Enums_CashBox : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MDGeneral_Enums_CashBox object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static MDGeneral_Enums_CashBox CreateMDGeneral_Enums_CashBox(global::System.Int32 id)
        {
            MDGeneral_Enums_CashBox mDGeneral_Enums_CashBox = new MDGeneral_Enums_CashBox();
            mDGeneral_Enums_CashBox.Id = id;
            return mDGeneral_Enums_CashBox;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CompanyUsingServiceId
        {
            get
            {
                return _CompanyUsingServiceId;
            }
            set
            {
                OnCompanyUsingServiceIdChanging(value);
                ReportPropertyChanging("CompanyUsingServiceId");
                _CompanyUsingServiceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyUsingServiceId");
                OnCompanyUsingServiceIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CompanyUsingServiceId;
        partial void OnCompanyUsingServiceIdChanging(Nullable<global::System.Int32> value);
        partial void OnCompanyUsingServiceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LocationId
        {
            get
            {
                return _LocationId;
            }
            set
            {
                OnLocationIdChanging(value);
                ReportPropertyChanging("LocationId");
                _LocationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationId");
                OnLocationIdChanged();
            }
        }
        private Nullable<global::System.Int32> _LocationId;
        partial void OnLocationIdChanging(Nullable<global::System.Int32> value);
        partial void OnLocationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MDGeneralModel", Name="MDGeneral_Enums_Currency")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MDGeneral_Enums_Currency : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MDGeneral_Enums_Currency object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="label">Initial value of the Label property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="measure">Initial value of the Measure property.</param>
        /// <param name="decimalPlaces">Initial value of the DecimalPlaces property.</param>
        /// <param name="inactive">Initial value of the Inactive property.</param>
        /// <param name="defaultCurrency">Initial value of the DefaultCurrency property.</param>
        /// <param name="lastChanged">Initial value of the LastChanged property.</param>
        public static MDGeneral_Enums_Currency CreateMDGeneral_Enums_Currency(global::System.Int32 id, global::System.String label, global::System.String name, global::System.Int32 measure, global::System.Int32 decimalPlaces, global::System.Boolean inactive, global::System.Boolean defaultCurrency, global::System.Byte[] lastChanged)
        {
            MDGeneral_Enums_Currency mDGeneral_Enums_Currency = new MDGeneral_Enums_Currency();
            mDGeneral_Enums_Currency.Id = id;
            mDGeneral_Enums_Currency.Label = label;
            mDGeneral_Enums_Currency.Name = name;
            mDGeneral_Enums_Currency.Measure = measure;
            mDGeneral_Enums_Currency.DecimalPlaces = decimalPlaces;
            mDGeneral_Enums_Currency.Inactive = inactive;
            mDGeneral_Enums_Currency.DefaultCurrency = defaultCurrency;
            mDGeneral_Enums_Currency.LastChanged = lastChanged;
            return mDGeneral_Enums_Currency;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Label
        {
            get
            {
                return _Label;
            }
            set
            {
                OnLabelChanging(value);
                ReportPropertyChanging("Label");
                _Label = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Label");
                OnLabelChanged();
            }
        }
        private global::System.String _Label;
        partial void OnLabelChanging(global::System.String value);
        partial void OnLabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Measure
        {
            get
            {
                return _Measure;
            }
            set
            {
                OnMeasureChanging(value);
                ReportPropertyChanging("Measure");
                _Measure = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Measure");
                OnMeasureChanged();
            }
        }
        private global::System.Int32 _Measure;
        partial void OnMeasureChanging(global::System.Int32 value);
        partial void OnMeasureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DecimalPlaces
        {
            get
            {
                return _DecimalPlaces;
            }
            set
            {
                OnDecimalPlacesChanging(value);
                ReportPropertyChanging("DecimalPlaces");
                _DecimalPlaces = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DecimalPlaces");
                OnDecimalPlacesChanged();
            }
        }
        private global::System.Int32 _DecimalPlaces;
        partial void OnDecimalPlacesChanging(global::System.Int32 value);
        partial void OnDecimalPlacesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Inactive
        {
            get
            {
                return _Inactive;
            }
            set
            {
                OnInactiveChanging(value);
                ReportPropertyChanging("Inactive");
                _Inactive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Inactive");
                OnInactiveChanged();
            }
        }
        private global::System.Boolean _Inactive;
        partial void OnInactiveChanging(global::System.Boolean value);
        partial void OnInactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean DefaultCurrency
        {
            get
            {
                return _DefaultCurrency;
            }
            set
            {
                OnDefaultCurrencyChanging(value);
                ReportPropertyChanging("DefaultCurrency");
                _DefaultCurrency = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DefaultCurrency");
                OnDefaultCurrencyChanged();
            }
        }
        private global::System.Boolean _DefaultCurrency;
        partial void OnDefaultCurrencyChanging(global::System.Boolean value);
        partial void OnDefaultCurrencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] LastChanged
        {
            get
            {
                return StructuralObject.GetValidValue(_LastChanged);
            }
            set
            {
                OnLastChangedChanging(value);
                ReportPropertyChanging("LastChanged");
                _LastChanged = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastChanged");
                OnLastChangedChanged();
            }
        }
        private global::System.Byte[] _LastChanged;
        partial void OnLastChangedChanging(global::System.Byte[] value);
        partial void OnLastChangedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CompanyUsingServiceId
        {
            get
            {
                return _CompanyUsingServiceId;
            }
            set
            {
                OnCompanyUsingServiceIdChanging(value);
                ReportPropertyChanging("CompanyUsingServiceId");
                _CompanyUsingServiceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyUsingServiceId");
                OnCompanyUsingServiceIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CompanyUsingServiceId;
        partial void OnCompanyUsingServiceIdChanging(Nullable<global::System.Int32> value);
        partial void OnCompanyUsingServiceIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MDGeneralModel", Name="MDGeneral_Enums_KindOfTransportation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MDGeneral_Enums_KindOfTransportation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MDGeneral_Enums_KindOfTransportation object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="lastChanged">Initial value of the LastChanged property.</param>
        /// <param name="inactive">Initial value of the Inactive property.</param>
        public static MDGeneral_Enums_KindOfTransportation CreateMDGeneral_Enums_KindOfTransportation(global::System.Int32 id, global::System.String name, global::System.Byte[] lastChanged, global::System.Boolean inactive)
        {
            MDGeneral_Enums_KindOfTransportation mDGeneral_Enums_KindOfTransportation = new MDGeneral_Enums_KindOfTransportation();
            mDGeneral_Enums_KindOfTransportation.Id = id;
            mDGeneral_Enums_KindOfTransportation.Name = name;
            mDGeneral_Enums_KindOfTransportation.LastChanged = lastChanged;
            mDGeneral_Enums_KindOfTransportation.Inactive = inactive;
            return mDGeneral_Enums_KindOfTransportation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] LastChanged
        {
            get
            {
                return StructuralObject.GetValidValue(_LastChanged);
            }
            set
            {
                OnLastChangedChanging(value);
                ReportPropertyChanging("LastChanged");
                _LastChanged = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastChanged");
                OnLastChangedChanged();
            }
        }
        private global::System.Byte[] _LastChanged;
        partial void OnLastChangedChanging(global::System.Byte[] value);
        partial void OnLastChangedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CompanyUsingServiceId
        {
            get
            {
                return _CompanyUsingServiceId;
            }
            set
            {
                OnCompanyUsingServiceIdChanging(value);
                ReportPropertyChanging("CompanyUsingServiceId");
                _CompanyUsingServiceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyUsingServiceId");
                OnCompanyUsingServiceIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CompanyUsingServiceId;
        partial void OnCompanyUsingServiceIdChanging(Nullable<global::System.Int32> value);
        partial void OnCompanyUsingServiceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Inactive
        {
            get
            {
                return _Inactive;
            }
            set
            {
                OnInactiveChanging(value);
                ReportPropertyChanging("Inactive");
                _Inactive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Inactive");
                OnInactiveChanged();
            }
        }
        private global::System.Boolean _Inactive;
        partial void OnInactiveChanging(global::System.Boolean value);
        partial void OnInactiveChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MDGeneralModel", Name="MDGeneral_Enums_Language")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MDGeneral_Enums_Language : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MDGeneral_Enums_Language object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="defaultLanguage">Initial value of the DefaultLanguage property.</param>
        /// <param name="inactive">Initial value of the Inactive property.</param>
        /// <param name="lastChanged">Initial value of the LastChanged property.</param>
        /// <param name="label">Initial value of the Label property.</param>
        public static MDGeneral_Enums_Language CreateMDGeneral_Enums_Language(global::System.Int32 id, global::System.String name, global::System.Boolean defaultLanguage, global::System.Boolean inactive, global::System.Byte[] lastChanged, global::System.String label)
        {
            MDGeneral_Enums_Language mDGeneral_Enums_Language = new MDGeneral_Enums_Language();
            mDGeneral_Enums_Language.Id = id;
            mDGeneral_Enums_Language.Name = name;
            mDGeneral_Enums_Language.DefaultLanguage = defaultLanguage;
            mDGeneral_Enums_Language.Inactive = inactive;
            mDGeneral_Enums_Language.LastChanged = lastChanged;
            mDGeneral_Enums_Language.Label = label;
            return mDGeneral_Enums_Language;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean DefaultLanguage
        {
            get
            {
                return _DefaultLanguage;
            }
            set
            {
                OnDefaultLanguageChanging(value);
                ReportPropertyChanging("DefaultLanguage");
                _DefaultLanguage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DefaultLanguage");
                OnDefaultLanguageChanged();
            }
        }
        private global::System.Boolean _DefaultLanguage;
        partial void OnDefaultLanguageChanging(global::System.Boolean value);
        partial void OnDefaultLanguageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Inactive
        {
            get
            {
                return _Inactive;
            }
            set
            {
                OnInactiveChanging(value);
                ReportPropertyChanging("Inactive");
                _Inactive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Inactive");
                OnInactiveChanged();
            }
        }
        private global::System.Boolean _Inactive;
        partial void OnInactiveChanging(global::System.Boolean value);
        partial void OnInactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] LastChanged
        {
            get
            {
                return StructuralObject.GetValidValue(_LastChanged);
            }
            set
            {
                OnLastChangedChanging(value);
                ReportPropertyChanging("LastChanged");
                _LastChanged = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastChanged");
                OnLastChangedChanged();
            }
        }
        private global::System.Byte[] _LastChanged;
        partial void OnLastChangedChanging(global::System.Byte[] value);
        partial void OnLastChangedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Label
        {
            get
            {
                return _Label;
            }
            set
            {
                OnLabelChanging(value);
                ReportPropertyChanging("Label");
                _Label = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Label");
                OnLabelChanged();
            }
        }
        private global::System.String _Label;
        partial void OnLabelChanging(global::System.String value);
        partial void OnLabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CompanyUsingServiceId
        {
            get
            {
                return _CompanyUsingServiceId;
            }
            set
            {
                OnCompanyUsingServiceIdChanging(value);
                ReportPropertyChanging("CompanyUsingServiceId");
                _CompanyUsingServiceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyUsingServiceId");
                OnCompanyUsingServiceIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CompanyUsingServiceId;
        partial void OnCompanyUsingServiceIdChanging(Nullable<global::System.Int32> value);
        partial void OnCompanyUsingServiceIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MDGeneralModel", Name="MDGeneral_Enums_Location")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MDGeneral_Enums_Location : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MDGeneral_Enums_Location object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static MDGeneral_Enums_Location CreateMDGeneral_Enums_Location(global::System.Int32 id)
        {
            MDGeneral_Enums_Location mDGeneral_Enums_Location = new MDGeneral_Enums_Location();
            mDGeneral_Enums_Location.Id = id;
            return mDGeneral_Enums_Location;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CompanyUsingServiceId
        {
            get
            {
                return _CompanyUsingServiceId;
            }
            set
            {
                OnCompanyUsingServiceIdChanging(value);
                ReportPropertyChanging("CompanyUsingServiceId");
                _CompanyUsingServiceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyUsingServiceId");
                OnCompanyUsingServiceIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CompanyUsingServiceId;
        partial void OnCompanyUsingServiceIdChanging(Nullable<global::System.Int32> value);
        partial void OnCompanyUsingServiceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WorkingHour
        {
            get
            {
                return _WorkingHour;
            }
            set
            {
                OnWorkingHourChanging(value);
                ReportPropertyChanging("WorkingHour");
                _WorkingHour = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WorkingHour");
                OnWorkingHourChanged();
            }
        }
        private global::System.String _WorkingHour;
        partial void OnWorkingHourChanging(global::System.String value);
        partial void OnWorkingHourChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MDGeneralModel", Name="MDGeneral_Enums_TimeZone")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MDGeneral_Enums_TimeZone : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MDGeneral_Enums_TimeZone object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="lastChanged">Initial value of the LastChanged property.</param>
        public static MDGeneral_Enums_TimeZone CreateMDGeneral_Enums_TimeZone(global::System.Int32 id, global::System.String name, global::System.Byte[] lastChanged)
        {
            MDGeneral_Enums_TimeZone mDGeneral_Enums_TimeZone = new MDGeneral_Enums_TimeZone();
            mDGeneral_Enums_TimeZone.Id = id;
            mDGeneral_Enums_TimeZone.Name = name;
            mDGeneral_Enums_TimeZone.LastChanged = lastChanged;
            return mDGeneral_Enums_TimeZone;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CompanyUsingServiceId
        {
            get
            {
                return _CompanyUsingServiceId;
            }
            set
            {
                OnCompanyUsingServiceIdChanging(value);
                ReportPropertyChanging("CompanyUsingServiceId");
                _CompanyUsingServiceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyUsingServiceId");
                OnCompanyUsingServiceIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CompanyUsingServiceId;
        partial void OnCompanyUsingServiceIdChanging(Nullable<global::System.Int32> value);
        partial void OnCompanyUsingServiceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] LastChanged
        {
            get
            {
                return StructuralObject.GetValidValue(_LastChanged);
            }
            set
            {
                OnLastChangedChanging(value);
                ReportPropertyChanging("LastChanged");
                _LastChanged = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastChanged");
                OnLastChangedChanged();
            }
        }
        private global::System.Byte[] _LastChanged;
        partial void OnLastChangedChanging(global::System.Byte[] value);
        partial void OnLastChangedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MDGeneralModel", Name="vEnums_Currency")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vEnums_Currency : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vEnums_Currency object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="label">Initial value of the Label property.</param>
        /// <param name="inactive">Initial value of the Inactive property.</param>
        public static vEnums_Currency CreatevEnums_Currency(global::System.Int32 id, global::System.String name, global::System.String label, global::System.Boolean inactive)
        {
            vEnums_Currency vEnums_Currency = new vEnums_Currency();
            vEnums_Currency.Id = id;
            vEnums_Currency.Name = name;
            vEnums_Currency.Label = label;
            vEnums_Currency.Inactive = inactive;
            return vEnums_Currency;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Label
        {
            get
            {
                return _Label;
            }
            set
            {
                OnLabelChanging(value);
                ReportPropertyChanging("Label");
                _Label = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Label");
                OnLabelChanged();
            }
        }
        private global::System.String _Label;
        partial void OnLabelChanging(global::System.String value);
        partial void OnLabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CompanyUsingServiceId
        {
            get
            {
                return _CompanyUsingServiceId;
            }
            set
            {
                OnCompanyUsingServiceIdChanging(value);
                ReportPropertyChanging("CompanyUsingServiceId");
                _CompanyUsingServiceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyUsingServiceId");
                OnCompanyUsingServiceIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CompanyUsingServiceId;
        partial void OnCompanyUsingServiceIdChanging(Nullable<global::System.Int32> value);
        partial void OnCompanyUsingServiceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientName
        {
            get
            {
                return _ClientName;
            }
            set
            {
                OnClientNameChanging(value);
                ReportPropertyChanging("ClientName");
                _ClientName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientName");
                OnClientNameChanged();
            }
        }
        private global::System.String _ClientName;
        partial void OnClientNameChanging(global::System.String value);
        partial void OnClientNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Inactive
        {
            get
            {
                return _Inactive;
            }
            set
            {
                OnInactiveChanging(value);
                ReportPropertyChanging("Inactive");
                _Inactive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Inactive");
                OnInactiveChanged();
            }
        }
        private global::System.Boolean _Inactive;
        partial void OnInactiveChanging(global::System.Boolean value);
        partial void OnInactiveChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MDGeneralModel", Name="vEnums_Language")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vEnums_Language : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vEnums_Language object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="label">Initial value of the Label property.</param>
        /// <param name="inactive">Initial value of the Inactive property.</param>
        public static vEnums_Language CreatevEnums_Language(global::System.Int32 id, global::System.String name, global::System.String label, global::System.Boolean inactive)
        {
            vEnums_Language vEnums_Language = new vEnums_Language();
            vEnums_Language.Id = id;
            vEnums_Language.Name = name;
            vEnums_Language.Label = label;
            vEnums_Language.Inactive = inactive;
            return vEnums_Language;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Label
        {
            get
            {
                return _Label;
            }
            set
            {
                OnLabelChanging(value);
                ReportPropertyChanging("Label");
                _Label = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Label");
                OnLabelChanged();
            }
        }
        private global::System.String _Label;
        partial void OnLabelChanging(global::System.String value);
        partial void OnLabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CompanyUsingServiceId
        {
            get
            {
                return _CompanyUsingServiceId;
            }
            set
            {
                OnCompanyUsingServiceIdChanging(value);
                ReportPropertyChanging("CompanyUsingServiceId");
                _CompanyUsingServiceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyUsingServiceId");
                OnCompanyUsingServiceIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CompanyUsingServiceId;
        partial void OnCompanyUsingServiceIdChanging(Nullable<global::System.Int32> value);
        partial void OnCompanyUsingServiceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientName
        {
            get
            {
                return _ClientName;
            }
            set
            {
                OnClientNameChanging(value);
                ReportPropertyChanging("ClientName");
                _ClientName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientName");
                OnClientNameChanged();
            }
        }
        private global::System.String _ClientName;
        partial void OnClientNameChanging(global::System.String value);
        partial void OnClientNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Inactive
        {
            get
            {
                return _Inactive;
            }
            set
            {
                OnInactiveChanging(value);
                ReportPropertyChanging("Inactive");
                _Inactive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Inactive");
                OnInactiveChanged();
            }
        }
        private global::System.Boolean _Inactive;
        partial void OnInactiveChanging(global::System.Boolean value);
        partial void OnInactiveChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MDGeneralModel", Name="vEnums_TimeZone")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vEnums_TimeZone : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vEnums_TimeZone object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static vEnums_TimeZone CreatevEnums_TimeZone(global::System.Int32 id, global::System.String name)
        {
            vEnums_TimeZone vEnums_TimeZone = new vEnums_TimeZone();
            vEnums_TimeZone.Id = id;
            vEnums_TimeZone.Name = name;
            return vEnums_TimeZone;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CompanyUsingServiceId
        {
            get
            {
                return _CompanyUsingServiceId;
            }
            set
            {
                OnCompanyUsingServiceIdChanging(value);
                ReportPropertyChanging("CompanyUsingServiceId");
                _CompanyUsingServiceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyUsingServiceId");
                OnCompanyUsingServiceIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CompanyUsingServiceId;
        partial void OnCompanyUsingServiceIdChanging(Nullable<global::System.Int32> value);
        partial void OnCompanyUsingServiceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientName
        {
            get
            {
                return _ClientName;
            }
            set
            {
                OnClientNameChanging(value);
                ReportPropertyChanging("ClientName");
                _ClientName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientName");
                OnClientNameChanged();
            }
        }
        private global::System.String _ClientName;
        partial void OnClientNameChanging(global::System.String value);
        partial void OnClientNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MDGeneralModel", Name="vEnumsCashBox")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vEnumsCashBox : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vEnumsCashBox object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static vEnumsCashBox CreatevEnumsCashBox(global::System.Int32 id)
        {
            vEnumsCashBox vEnumsCashBox = new vEnumsCashBox();
            vEnumsCashBox.Id = id;
            return vEnumsCashBox;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CompanyUsingServiceId
        {
            get
            {
                return _CompanyUsingServiceId;
            }
            set
            {
                OnCompanyUsingServiceIdChanging(value);
                ReportPropertyChanging("CompanyUsingServiceId");
                _CompanyUsingServiceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyUsingServiceId");
                OnCompanyUsingServiceIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CompanyUsingServiceId;
        partial void OnCompanyUsingServiceIdChanging(Nullable<global::System.Int32> value);
        partial void OnCompanyUsingServiceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MDGeneralModel", Name="vvEnumsCashBox")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vvEnumsCashBox : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vvEnumsCashBox object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static vvEnumsCashBox CreatevvEnumsCashBox(global::System.Int32 id)
        {
            vvEnumsCashBox vvEnumsCashBox = new vvEnumsCashBox();
            vvEnumsCashBox.Id = id;
            return vvEnumsCashBox;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CompanyUsingServiceId
        {
            get
            {
                return _CompanyUsingServiceId;
            }
            set
            {
                OnCompanyUsingServiceIdChanging(value);
                ReportPropertyChanging("CompanyUsingServiceId");
                _CompanyUsingServiceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyUsingServiceId");
                OnCompanyUsingServiceIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CompanyUsingServiceId;
        partial void OnCompanyUsingServiceIdChanging(Nullable<global::System.Int32> value);
        partial void OnCompanyUsingServiceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
    }

    #endregion

    
}
