//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaWebCommodityBookkeeping
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class alphascore_bisl4Entities : DbContext
    {
        public alphascore_bisl4Entities()
            : base("name=alphascore_bisl4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<IzborSortimenata> IzborSortimenata { get; set; }
        public DbSet<Pesticidi> Pesticidi { get; set; }
    }
}
