//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaWebCommodityBookkeeping
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzborSortimenata
    {
        public int Id { get; set; }
        public string Sorta { get; set; }
        public string DuzinaVegetacije { get; set; }
        public string OptimalniRokSjetve { get; set; }
        public string PreporucenaGustoca { get; set; }
        public string Napomena { get; set; }
        public string Predstavnik { get; set; }
        public string Katalog { get; set; }
    }
}
