//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaWebCommodityBookkeeping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pesticidi
    {
        public int Id { get; set; }
        public string IDFIS { get; set; }
        public string Kultura { get; set; }
        public string NazivStetocine { get; set; }
        public string NazivSZB { get; set; }
        public string AktivnaTvar { get; set; }
        public string Doza { get; set; }
        public Nullable<double> KarencaDan { get; set; }
        public string MaksimalniBrojTretiranja { get; set; }
        public string Klasa { get; set; }
        public string VlasnikRegistracije { get; set; }
        public string SZB { get; set; }
        public string Predstavnik { get; set; }
        public string DatumIsteka { get; set; }
        public string VrijemePrimjene { get; set; }
        public string Djelovanje { get; set; }
    }
}
